[package]
name = "beet_flow"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
# reflect requires trait upcasting so is nightly only
reflect = ["dep:heck", "dep:serde", "scene", "bevy/serialize"]
scene = ["bevy/bevy_scene"]
# default = ["bevyhub"]
bevyhub = ["dep:bevyhub", "bevyhub/net", "bevyhub/core"]

[dependencies]
beet_flow_macros.workspace = true
bevyhub = { workspace = true, optional = true }

bevy.workspace = true

log.workspace = true
anyhow.workspace = true
extend.workspace = true
serde = { workspace = true, optional = true }
heck = { workspace = true, optional = true }

[dev-dependencies]
pretty_env_logger.workspace = true
ron.workspace = true
sweet = { workspace = true, features = ["test", "bevy"] }
